### PR TITLE
Basic typescript support

### PR DESCRIPTION
**Pull request by sinxwal**

### CODE REVIEW

**Comment by bberak** [comment]
Awesome, thanks @sinxwal!

Would this be related to #14 (I'm not a typescript guy)?

**Comment by sinxwal** [comment]
Yes. However it needs more typings (removing 'any').

**Comment by bberak** [comment]
Well it's a great start! Thanks @sinxwal - I've just published `0.12.0` with your changes.

**Comment by sinxwal** [comment]
@bberak Thank you for merging the PR.

**Comment by bberak** [comment]
Don't mention it @sinxwal  :)

**Pull request merged**
