### PR TITLE
replace old filenames for index.js in README

### PR DESCRIPTION
**Pull request by emilioicai**
Most of RN users nowadays use a version which doesn't have two separate index files. Please consider updating the docs accordingly.

### CODE REVIEW

**Comment by bberak** [comment]
Hi @emilioicai,

What's the common practice nowadays for switching between iOS and Android specific code?

**Comment by emilioicai** [comment]
Since React Native 0.57 the whole codebase is shared between both platforms. If you want to separate pieces of code for a specific platform you can use `Platform` and do something like this:

```
import Platform from 'react-native'

if(Platform.OS === 'ios') {
    // do specific ios stuff here
}
```

**Comment by bberak** [comment]
I think we should replace all instances of `index.ios.js` and `index.android.js`

**Comment by bberak** [comment]
pokes @emilioicai

**Pull request closed without merging**
