### PR TITLE
Fix long press handling

### PR DESCRIPTION
**Pull request by anhba817**
Add move sensitivity parameter to touch processor to handle the case
real Android device is too sensitive, lead to long press events is
not detected when user press and hold

### CODE REVIEW

**Comment by bberak** [comment]
Hi @anhba817,

Thanks for your contribution, I really appreciate it..

Can you explain how your change works? In particular, I was wondering about this line: `filter(e => e.delta.pageX**2 + e.delta.pageY**2 > moveSensitivity**2)`. Are you basically using the distance formula to determine whether the move should be considered?

It would be great if the default `mouseSensitivty` setting doesn't change the behaviour of the `DefaultTouchProcessor`. Ideally, we want users who are not affected by issue #37 not to notice a difference when they uprgrade to the latest version of RNGE.. Should we set it to zero?

What is the expected range of numbers to use for the `mouseSensitivity` parameter? 0-1000? I'd like to add a bit about this in the documentation, but also so I can test out the range using an iOS device.

Cheers!

**Comment by anhba817** [comment]
Hi @bberak,
Yes, I use the distance formula to determine whether the move should be considered or not. The moveSensitivity here actually a threshold. I agree with you that we should set it to zero to make sure the change not affect to others.
About the range of moveSensitivity, I don't know exactly. We have to keep it large enough to ignore the "fake move" , and small enough to not raise the long-press event when user already move their finger. Do you know in which unit the pageX and pageY are measured ? I thought it was pixels, but when print them out, I see they are not integers. I think if we can convert them to distance units like inch or cm, we can define the threshold easier base on these unit.
Regards,

**Comment by bberak** [comment]
Hi @anhba817,

The `pageX` and `pageY` are measured in points (approximated 1/163 of an inch - don't quote me). I think using the name `threshold` in the argument makes sense. Let me merge this in and I'll update the argument name and update the docs.

**Comment by bberak** [comment]
Hi @anhba817,

I reverted this PR in the master branch for a couple of reasons.

I think this code will duplicate the "move" events in the touches array:

```javascript
let subscriptions = [
   touchStart,
   touchEnd,
   touchPress,
   longTouch,
   touchMoveDelta,
   realMove,
   longTouch
].map(x => x.subscribe(y => touches.push(y)));
```

The code above will push events from `realMove` and `touchMoveDelta` into touches. I don't this is quite what we want.

Also, I think we want the sensitivity threshold to affect the `touchMoveDelta` stream. Therefore, I was thinking, maybe we can add one line to fix up this whole problem:

```javascript
import { Observable, Subject, empty, of, merge } from "rxjs";
import {
	mergeMap,
	first,
	timeoutWith,
	delay,
	takeUntil,
	map,
	groupBy,
	filter,
	pairwise
} from "rxjs/operators";

export default ({
	triggerPressEventBefore = 200,
	triggerLongPressEventAfter = 700,
	moveThreshold = 0
}) => {
	return touches => {
		let touchStart = new Subject().pipe(
			map(e => ({ id: e.identifier, type: "start", event: e }))
		);
		let touchMove = new Subject().pipe(
			map(e => ({ id: e.identifier, type: "move", event: e }))
		);
		let touchEnd = new Subject().pipe(
			map(e => ({ id: e.identifier, type: "end", event: e }))
		);

		let touchPress = touchStart.pipe(
			mergeMap(e =>
				touchEnd.pipe(
					first(x => x.id === e.id),
					timeoutWith(triggerPressEventBefore, empty())
				)
			),
			map(e => ({ ...e, type: "press" }))
		);

		let touchMoveDelta = merge(touchStart, touchMove, touchEnd).pipe(
			groupBy(e => e.id),
			mergeMap(group =>
				group.pipe(
					pairwise(),
					map(([e1, e2]) => {
						if (e1.type !== "end" && e2.type === "move") {
							return {
								id: group.key,
								type: "move",
								event: e2.event,
								delta: {
									locationX: e2.event.locationX - e1.event.locationX,
									locationY: e2.event.locationY - e1.event.locationY,
									pageX: e2.event.pageX - e1.event.pageX,
									pageY: e2.event.pageY - e1.event.pageY,
									timestamp: e2.event.timestamp - e1.event.timestamp
								}
							};
						}
					}),
					filter(e => e),
                                        //-- Below is the only line I've added (this is your algorithm)
					filter(e => e.delta.pageX ** 2 + e.delta.pageY ** 2 > moveThreshold ** 2)
				)
			)
		);

		let longTouch = touchStart.pipe(
			mergeMap(e =>
				of(e).pipe(
					delay(triggerLongPressEventAfter),
					takeUntil(
                                                //-- I've replaced touchMove with touchMoveDelta below
						merge(touchMoveDelta, touchEnd).pipe(
							first(x => x.id === e.id)
						)
					)
				)
			),
			map(e => ({ ...e, type: "long-press" }))
		);

		let subscriptions = [
			touchStart,
			touchEnd,
			touchPress,
			longTouch,
			touchMoveDelta
		].map(x => x.subscribe(y => touches.push(y)));

		return {
			process(type, event) {
				switch (type) {
					case "start":
						touchStart.next(event);
						break;
					case "move":
						touchMove.next(event);
						break;
					case "end":
						touchEnd.next(event);
						break;
				}
			},
			end() {
				subscriptions.forEach(x => x.unsubscribe());
				touchStart.unsubscribe();
				touchMove.unsubscribe();
				touchEnd.unsubscribe();
				touchPress.unsubscribe();
				longTouch.unsubscribe();
			}
		};
	};
};
```

Essentially, all this does is filter the `touchMoveDelta` events that don't break the threshold, and subscribes the `longTouch` stream to the `touchMoveDelta` stream instead of just `touchMove`. That code is based entirely on your idea, I've just tried to simplify it a bit. I was hoping you can test the above code on your device to see if it works - and if so can you update your pull request or create a new pull request.

Sorry that this has been such a painful process, but I really want the touch processing to be correct and as simple as possible because it's such an important component.

**Comment by anhba817** [comment]
Hi @bberak,
Great, I have tested it again with your new code and it works fine.
I used to think about modifying touchMoveDelta stream before, but I was afraid that this will affect to the smoothness when peoples move their fingers, so I chose create a new stream but forget that I would duplicate the move events.
After testing, I see that the threshold does not have large impact on smoothness as I thought, at least I cannot see any delay when I moved my fingers. So I think modifying touchMoveDelta is a good solution.
I created a new pull request.
Thanks

**Pull request merged**
