### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
I noticed that it was a bit hard to understand how to use your engine given the current readme. I have proposed some changes that I believe will help newcomers understand how to use RNGE better, based on my own experience trying to learn it.

I moved some sections around. A couple sections were redundant and have been deleted. Some phrasing has been changed.

[Here's the rendered markdown](https://github.com/evanram/react-native-game-engine/tree/patch-1/README.md).  
(I personally find it difficult understand what's going on with a big ol' markdown diff. 🙃)

### CODE REVIEW

**Comment by bberak** [comment]
Thanks for the effort @evanram - I'll take a look and try merge this over the weekend. Cheers!

**Comment by ghost** [comment]
Awesome, let me know what you think. Note that I removed the index as the page flows well without one (in my opinion).

**Comment by ghost** [comment]
Friendly ping, @bberak

**Comment by bberak** [comment]
Hey @evanram,

Sorry I totally dropped the ball on this one - I should've gotten back to you months ago. I've been working on the web version of the engine and some games on the side. Back into the swing of things on the RN side now.

I noticed that you totally removed the FAQ from the README - was the info there totally useless? Or should I place it somewhere else?

All good if you don't have the time or will (or patience!) to respond either. That is totally understandable.

**Pull request closed without merging**
